# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hostname', models.TextField(blank=True, null=True)),
                ('ip', models.TextField(blank=True, null=True)),
                ('area', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hostname', models.TextField(blank=True, null=True)),
                ('ip', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'switch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Switchport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('port', models.TextField(blank=True, null=True)),
                ('ip', models.TextField(blank=True, null=True)),
                ('duplex', models.TextField(blank=True, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'switchport',
                'managed': False,
            },
        ),
    ]
